const bcrypt = require('bcryptjs');

const data = {
  users: [
    {
      name: 'Karthik',
      email: 'admin@example.com',
      password: bcrypt.hashSync('123456'),
      isAdmin: true,
    },
    {
      name: 'John',
      email: 'user@example.com',
      password: bcrypt.hashSync('123456'),
      isAdmin: false,
    },
  ],
  products: [
    {
      // _id: '1',
      name: 'Louis Philippe Shirt',
      slug: 'louis-philippe-shirt',
      category: 'Shirts',
      image: '/images/product1.jpg',
      price: 1619,
      countInStock: 10,
      brand: 'Louis Philippe',
      rating: 4.5,
      numReviews: 10,
      description: 'Regular Fit Solid All Day Comfort Cotton Effortless Ironing Formal Shirt',
    },
    {
      //_id: '2',
      name: 'Red Tape Shirt',
      slug: 'red-tape-shirt',
      category: 'Shirts',
      image: '/images/product2.jpg',
      price: 1167,
      countInStock: 20,
      brand: 'Red Tape',
      rating: 5,
      numReviews: 1,
      description: 'Sports Slim fit Printed 100% Cotton Casual Shirt',
    },
    {
      //_id: '3',
      name: 'Tommy Hilfiger Shirt',
      slug: 'tommy-hilfiger-shirt',
      category: 'Shirts',
      image: '/images/product3.jpg',
      price: 2299,
      countInStock: 0,
      brand: 'Tommy Hilfiger',
      rating: 3.7,
      numReviews: 14,
      description: 'Sports Slim Fit Premium Fabric, Superior Craftsmanship Casual Shirt',
    },
    {
      //_id: '4',
      name: 'Peter England Shirt',
      slug: 'peter-england-shirt',
      category: 'Shirts',
      image: '/images/product4.jpg',
      price: 1199,
      countInStock: 15,
      brand: 'Peter England',
      rating: 3.6,
      numReviews: 27,
      description: 'Jeans Slim Fit Denim Classic Premium Casual Shirt',
    },
    {
      //_id: '5',
      name: 'Allen Solly Shirt',
      slug: 'allen-solly-shirt',
      category: 'Shirts',
      image: '/images/product5.jpg',
      price: 759,
      countInStock: 5,
      brand: 'Allen Solly',
      rating: 3.9,
      numReviews: 7959,
      description: "Men's Slim Fit Shirt",
    },
    {
      //_id: '6',
      name: 'Dennis Lingo Shirt',
      slug: 'dennis-lingo-shirt',
      image: '/images/product6.jpg',
      price: 499,
      countInStock: 12,
      brand: 'Dennis Lingo',
      rating: 3.8,
      numReviews: 38504,
      description: "Men's Solid Slim Fit Cotton Casual Shirt with Spread Collar & Full Sleeves",
    },
  ],
};

// Export the data object
module.exports = data;
